# Copyright 1999-2025 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Maxframe K8S envs
MAXFRAME_NAMESPACE = "MAXFRAME_NAMESPACE"

# Maxframe Service common envs
MAXFRAME_HTTP_PORT_FILE = "MAXFRAME_PROXY_PORT_FILE"
MAXFRAME_INSIDE_TASK = "MAXFRAME_INSIDE_TASK"
MAXFRAME_SERVICE_BASE_URL = "MF_SERVICE_BASE_URL"
MAXFRAME_SERVICE_ALLOW_ORIGIN = "MAXFRAME_SERVICE_ALLOW_ORIGIN"
MAXFRAME_SERVICE_LISTEN_ADDRESS = "MAXFRAME_SERVICE_LISTEN_ADDRESS"
MAXFRAME_SERVICE_LOG_CONFIG_FILE = "MAXFRAME_SERVICE_LOG_CONFIG_FILE"
MAXFRAME_SERVICE_PORT = "MAXFRAME_SERVICE_PORT"
MAXFRAME_SERVICE_PORT_RETRIES = "MAXFRAME_SERVICE_PORT_RETRIES"
MAXFRAME_USER_LOG_CONFIG_FILE = "MAXFRAME_USER_LOG_CONFIG_FILE"

# ODPS envs
ODPS_BEARER_TOKEN = "ODPS_BEARER_TOKEN"
ODPS_BEARER_TOKEN_FILE = "ODPS_BEARER_TOKEN_FILE"
ODPS_BEARER_TOKEN_TIMESTAMP_FILE = "ODPS_BEARER_TOKEN_TIMESTAMP_FILE"
ODPS_PROJECT_NAME = "ODPS_PROJECT_NAME"
ODPS_ENDPOINT = "ODPS_ENDPOINT"
ODPS_TUNNEL_ENDPOINT = "ODPS_TUNNEL_ENDPOINT"
ODPS_NAMESPACE = "ODPS_NAMESPACE"
ODPS_STORAGE_API_ENDPOINT = "ODPS_STORAGE_API_ENDPOINT"
