# Copyright 1999-2026 Alibaba Group Holding Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Callable, Optional, Type

def ceildiv(x: int, y: int) -> int: ...
def to_str(s, encoding: Optional[str] = None) -> str: ...
def to_binary(s, encoding: Optional[str] = None) -> bytes: ...
def to_text(s, encoding: str = "utf-8"): ...
def get_user_call_point(): ...
def register_tokenizer(cls: Type, handler: Callable) -> None: ...
def reset_id_random_seed() -> None: ...
def new_random_id(byte_len: int) -> bytes: ...
def tokenize(*args, **kwargs) -> str: ...
def tokenize_int(*args, **kwargs) -> int: ...

class Timer:
    def __enter__(self): ...
    def __exit__(self, *_): ...

class TypeDispatcher:
    def __init__(self): ...
    def register(self, type_: Type, handler: Callable) -> None: ...
    def unregister(self, type_: Type) -> None: ...
    def dump_handlers(self) -> tuple: ...
    def load_handlers(self, handlers, lazy_handlers, inherit_handlers) -> None: ...
    def get_handler(self, type_: Type) -> Callable: ...
    def __call__(self, obj: Any, *args, **kwargs): ...
    @staticmethod
    def reload_all_lazy_handlers(): ...
