name: MaxFrame CD for PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, windows-latest]
        arch: [auto]
        include:
          - os: ubuntu-latest
            arch: aarch64
          - os: macos-13
            arch: universal2

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: ${{ matrix.arch == 'aarch64' }}
        uses: docker/setup-qemu-action@v1

      - name: Install Python
        uses: actions/setup-python@v4

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.16.5

      - name: "Build wheels"
        run: python -m cibuildwheel --output-dir ./wheelhouse ./core
        env:
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: pp* *-musllinux* *i686 cp36-* cp312-*
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux2014

      - name: Build source
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'auto'}}
        run: |
          pip install build
          (cd core; python -m build --sdist --outdir ../wheelhouse .)

      - name: Patch Install Python
        uses: actions/setup-python@v4
        if: ${{ startsWith(matrix.os, 'macos-') }}
        with:
          python-version: '3.8'

      - name: Release to pypi
        shell: bash
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          if [[ "$GITHUB_REPOSITORY" == "aliyun/alibabacloud-odps-maxframe-client" ]]; then
            PYPI_REPO="https://upload.pypi.org/legacy/"
          else
            PYPI_REPO="https://test.pypi.org/legacy/"
          fi
          echo "[distutils]"             > ~/.pypirc
          echo "index-servers ="        >> ~/.pypirc
          echo "    pypi"               >> ~/.pypirc
          echo "[pypi]"                 >> ~/.pypirc
          echo "repository=$PYPI_REPO"  >> ~/.pypirc
          python -m pip install twine
          python -m twine upload -r pypi --skip-existing wheelhouse/*

      - name: Upload artifacts to github
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: wheels
          path: ./wheelhouse
